In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
df = pd.read_csv('train.csv',',')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
Id                     10000 non-null int64
age                    10000 non-null float64
years_of_experience    10000 non-null float64
lesson_price           10000 non-null float64
qualification          10000 non-null float64
physics                10000 non-null float64
chemistry              10000 non-null float64
biology                10000 non-null float64
english                10000 non-null float64
geography              10000 non-null float64
history                10000 non-null float64
mean_exam_points       10000 non-null float64
choose                 10000 non-null int64
dtypes: float64(11), int64(2)
memory usage: 1015.7 KB


In [6]:
df.describe()

Id           age  years_of_experience  lesson_price  \
count  10000.00000  10000.000000         10000.000000  10000.000000   
mean    4999.50000     45.800900             1.974800   1702.440000   
std     2886.89568      8.030274             1.766883    523.789062   
min        0.00000     23.000000             0.000000    200.000000   
25%     2499.75000     40.000000             0.000000   1300.000000   
50%     4999.50000     46.000000             2.000000   1550.000000   
75%     7499.25000     51.000000             3.000000   2150.000000   
max     9999.00000     68.000000             9.000000   3950.000000   

       qualification      physics     chemistry       biology       english  \
count   10000.000000  10000.00000  10000.000000  10000.000000  10000.000000   
mean        1.724300      0.37060      0.121500      0.117200      0.059100   
std         0.798845      0.48299      0.326724      0.321675      0.235824   
min         1.000000      0.00000      0.000000      0.000000      0.000000   
25%         1.000000      0.00000      0.000000      0.000000      0.000000   
50%         2.000000      0.00000      0.000000      0.000000      0.000000   
75%         2.000000      1.00000      0.000000      0.000000      0.000000   
max         4.000000      1.00000      1.000000      1.000000      1.000000   

         geography       history  mean_exam_points        choose  
count  10000.00000  10000.000000      10000.000000  10000.000000  
mean       0.02770      0.018000         64.435200      0.110900  
std        0.16412      0.132958         13.595024      0.314024  
min        0.00000      0.000000         33.000000      0.000000  
25%        0.00000      0.000000         55.000000      0.000000  
50%        0.00000      0.000000         63.000000      0.000000  
75%        0.00000      0.000000         74.000000      0.000000  
max        1.00000      1.000000        100.000000      1.000000

In [7]:
df.head()

Id   age  years_of_experience  lesson_price  qualification  physics  \
0   0  35.0                  0.0        2150.0            2.0      0.0   
1   1  52.0                  2.0        1250.0            2.0      1.0   
2   2  29.0                  3.0        1750.0            1.0      1.0   
3   3  33.0                  3.0        1050.0            1.0      0.0   
4   4  46.0                  3.0        2250.0            2.0      1.0   

   chemistry  biology  english  geography  history  mean_exam_points  choose  
0        0.0      0.0      0.0        0.0      0.0              74.0       0  
1        0.0      1.0      0.0        0.0      1.0              57.0       1  
2        0.0      0.0      0.0        0.0      0.0              66.0       0  
3        0.0      0.0      0.0        0.0      0.0              66.0       1  
4        0.0      0.0      0.0        0.0      0.0              73.0       0

In [8]:
y = df['mean_exam_points'].values
y

array([74., 57., 66., ..., 59., 72., 40.])

In [11]:
X = df.loc[:, df.columns != 'choose']
X = X.values[:,1:]
X = X.T
X

array([[3.50e+01, 5.20e+01, 2.90e+01, ..., 4.40e+01, 4.10e+01, 4.10e+01],
       [0.00e+00, 2.00e+00, 3.00e+00, ..., 5.00e+00, 0.00e+00, 5.00e+00],
       [2.15e+03, 1.25e+03, 1.75e+03, ..., 1.75e+03, 1.70e+03, 1.20e+03],
       ...,
       [0.00e+00, 0.00e+00, 0.00e+00, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.00e+00, 0.00e+00, 0.00e+00],
       [7.40e+01, 5.70e+01, 6.60e+01, ..., 5.90e+01, 7.20e+01, 4.00e+01]])

In [31]:
def calc_logloss(y, y_pred):
    for i in range(y_pred.shape[0]):
        if y_pred[i]==1:
            y_pred[i]-=1e-4
        elif y_pred[i]==0:
            y_pred[i]+=1e-4
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    err = np.sum(err)
    return err

In [22]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-0.9*z))
    return res

In [32]:
def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [33]:
W = eval_model(X, y, iterations=5000, alpha=1e-4)

500 [ 1.45789008e+02  6.37523557e+00  5.65999545e+03  7.40686348e+00
  1.00240348e+00  1.57853651e-01  1.95960840e+00  9.55875025e-01
 -3.78649247e-01  6.00135134e-01  2.13150204e+02] -584.2533397221931
1000 [ 2.91081302e+02  1.28887354e+01  1.13193432e+04  1.32906971e+01
  2.23896033e+00  5.49844258e-01  2.34000399e+00  1.14431532e+00
 -2.87824109e-01  6.57710224e-01  4.26763827e+02] -584.2533397221931
1500 [ 4.36373596e+02  1.94022353e+01  1.69786910e+04  1.91745307e+01
  3.47551718e+00  9.41834866e-01  2.72039957e+00  1.33275562e+00
 -1.96998970e-01  7.15285314e-01  6.40377449e+02] -584.2533397221931
2000 [ 5.81665890e+02  2.59157352e+01  2.26380387e+04  2.50583643e+01
  4.71207404e+00  1.33382547e+00  3.10079516e+00  1.52119591e+00
 -1.06173832e-01  7.72860404e-01  8.53991071e+02] -584.2533397221931
2500 [ 7.26958184e+02  3.24292351e+01  2.82973865e+04  3.09421980e+01
  5.94863089e+00  1.72581608e+00  3.48119075e+00  1.70963621e+00
 -1.53486934e-02  8.30435494e-01  1.06760469e+03] 

In [34]:
def calc_pred(W, X):
    z = np.dot(W, X)
    y_pred = sigmoid(z)
    for i in range(X.shape[1]):
        if y_pred[i]>0.5:
            y_pred[i]= 1
        else:
            y_pred[i]= 0 
    return y_pred

In [36]:
y_pred = calc_pred(W,X)
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

In [41]:
y_pred.shape

(10000,)

In [42]:
#доля правильных ответов
a = np.sum(y_pred==y)/len(y)
a

0.0

In [49]:
#матрица ошибок
TP = np.sum(np.logical_and(y == 1, y_pred == 1))
TN = np.sum(np.logical_and(y == 0, y_pred == 1))
FP = np.sum(np.logical_and(y == 0, y_pred == 0))
FN = np.sum(np.logical_and(y == 1, y_pred == 0))
print(f'TP={TP}, TN={TN}, FP={FP}, FN={FN}')

TP=0, TN=0, FP=0, FN=0


In [51]:
#(False Positive Rate) - отношение числа ложных срабатываний к общему размеру отрицательного класса
FPR = FP / (FP+TN)
FPR

C:\Users\sych_\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in long_scalars
  


nan

In [52]:
#(True Positive Rate) - отношение числа верных срабатываний к размеру положительного класса
TPR = TP / (TP+FN)
TPR

C:\Users\sych_\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in long_scalars
  


nan

In [53]:
from numpy import trapz  # используем эту функцию для расчета площади под кривой

AUC_ROC = trapz(TPR, x = FPR, dx=0.1)

plt.title('ROC curve')
plt.ylim(0, 1.05)
plt.xlabel('FPR')
plt.ylabel('TPR')
plt.grid()
plt.legend(' ', title=f'AUC-ROC={AUC_ROC:.3f}', loc='lower right')
plt.plot(FPR, TPR)

AxisError: axis -1 is out of bounds for array of dimension 0